var EntrePanes ={
"type": "FeatureCollection",
"name": "EntrePanes",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 1, "Nombre": "Jack House (Centro)", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "La hamburguesería favorita de los guleros. La mejor versión de burger vegetariana. Hamburguesas y lomos. Opción de medallón de soja para todas burger." }, "geometry": { "type": "Point", "coordinates": [ -68.850534101112146, -32.891046416461315 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Burgery (Arístides)", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Hamburguesería. Opción vegetariana para todas las burgers." }, "geometry": { "type": "Point", "coordinates": [ -68.853427295532697, -32.892551082325454 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "The Factory Burger", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Hamburguesería. Opciones vegetarianas, veganas y sin TACC." }, "geometry": { "type": "Point", "coordinates": [ -68.854182302017151, -32.883822941138796 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "The Nook", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Buenas hamburguesas. Ricos postres para comer en el lugar o para llevar. Opciones vegetarianas." }, "geometry": { "type": "Point", "coordinates": [ -68.856667242535266, -32.883638056169602 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Chachingo Urban Tap", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Cerveza artesanal, hamburguesas y pizzas. Opción vegetariana." }, "geometry": { "type": "Point", "coordinates": [ -68.856447082165772, -32.883644486957607 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Burgery (Il Mercato)", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Hamburguesería. Opción vegetariana para todas las burgers." }, "geometry": { "type": "Point", "coordinates": [ -68.79251705765914, -32.992464056572572 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "The Nook (Il Mercato)", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Buenas hamburguesas. Ricos postres para comer en el lugar o para llevar. Opciones vegetarianas." }, "geometry": { "type": "Point", "coordinates": [ -68.792490255527213, -32.992197506662094 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "The Casero", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Excelentes lomos, hamburguesas y pizzas a la parrilla. Opciones para vegetarianos y celíacos. Muy buena atención." }, "geometry": { "type": "Point", "coordinates": [ -68.878351842404612, -32.982922353033352 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Jack House (Chacras Park)", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "La hamburguesería favorita de los guleros. La mejor versión de burger vegetariana. Hamburguesas y lomos. Opción de medallón de soja para todas burger." }, "geometry": { "type": "Point", "coordinates": [ -68.877296029850029, -32.968036071356117 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Chachingo (Palmares)", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Hamburguesas\\Hamburguesas.shp|layername=Hamburguesas", "Descrip": "Cócteles, cerveza artesanal. Lomos, hamburguesas y pizzas. Opción vegetariana." }, "geometry": { "type": "Point", "coordinates": [ -68.858817874317765, -32.955034821474705 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Torito", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Lomos-Sandwichs\\Lomos.shp|layername=Lomos", "Descrip": "Lomos, hamburguesas, sandwiches a la parrilla, cócteles." }, "geometry": { "type": "Point", "coordinates": [ -68.852036934938496, -32.883896493095378 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "El Asadito", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Lomos-Sandwichs\\Lomos.shp|layername=Lomos", "Descrip": "Lomos y parrilla. Opciones vegetarianas." }, "geometry": { "type": "Point", "coordinates": [ -68.856224050139303, -32.883777925703562 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Punta del Lago", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Lomos-Sandwichs\\Lomos.shp|layername=Lomos", "Descrip": "Sandwiches y lomos." }, "geometry": { "type": "Point", "coordinates": [ -68.868541544202003, -32.889938396975197 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "La Vizcachera", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Lomos-Sandwichs\\Lomos.shp|layername=Lomos", "Descrip": "Sandwiches y lomos en el Parque." }, "geometry": { "type": "Point", "coordinates": [ -68.869860591980895, -32.885691865365992 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Almacén 184", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Lomos-Sandwichs\\Lomos.shp|layername=Lomos", "Descrip": "Lomos, sandwiches, hamburguesas y pizzas, milanesas. Opciones vegetarianas." }, "geometry": { "type": "Point", "coordinates": [ -68.848581613661196, -32.926099213931266 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "Las Chapas", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Lomos-Sandwichs\\Lomos.shp|layername=Lomos", "Descrip": "Tapas, pastas, cócteles." }, "geometry": { "type": "Point", "coordinates": [ -68.858760441177907, -32.954838840385456 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "El Rincón Sandwich", "path": "C:\\Users\\PC Ultimate\\Documents\\Mapa Gula\\Lomos-Sandwichs\\Lomos.shp|layername=Lomos", "Descrip": "Excelentes lomos, buenos precios." }, "geometry": { "type": "Point", "coordinates": [ -68.796854216937817, -32.910011909682289 ] } }
]
}
